# Generated by Django 4.2.30 on 2026-07-09 06:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('style_vector', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('samples', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'style_profiles',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='GenerationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('result', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_records', to='styles.styleprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'generation_records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='styleprofile',
            index=models.Index(fields=['user', 'name'], name='style_profiles_user_name_idx'),
        ),
    ]
