# Generated by Django 4.2.30 on 2026-08-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0004_generationrecord_feedback'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generationrecord',
            index=models.Index(fields=['user', 'created_at'], name='genrec_user_created_idx'),
        ),
    ]
