# Generated by Django 4.2.30 on 2026-08-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_scene_relationship_style_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'updated_at'], name='chat_sessions_user_updated_idx'),
        ),
    ]
