# Generated by Django 4.2.30 on 2026-07-09 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('risks', models.JSONField(blank=True, default=list)),
                ('report', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_reviews',
                'ordering': ('-created_at',),
            },
        ),
    ]
