# Generated by Django 4.2.30 on 2026-08-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentreview_doc_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['user', 'created_at'], name='docrev_user_created_idx'),
        ),
    ]
