# Generated by Django 4.2.30 on 2026-07-09 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_templates',
                'ordering': ('module', '-updated_at'),
                'indexes': [models.Index(fields=['module', 'is_active'], name='prompt_module_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('module', 'version'), name='prompt_module_version_uniq'),
        ),
    ]
