# Generated by Django 4.2.30 on 2026-08-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_seed_document_review_prompt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['module', 'version', 'is_active'], name='prompt_mod_ver_active_idx'),
        ),
    ]
